name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - shapely
  - scikit-learn
  - fiona
  - seaborn
  - scipy
  - geopandas
  - matplotlib
  - pandas
  - papermill
  - ipykernel