name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - scikit-learn<1.4
  - numpy
  - scipy
  - matplotlib
  - pandas
  - statsmodels
  - pmdarima
  - papermill
  - ipykernel
