name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - nbconvert
  - numpy
  - pandas
  - pmdarima
  - statsmodels
  - scikit-learn<1.4
  - scipy
  - matplotlib
  - papermill
  - ipykernel
