name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - pandas
  - numpy<=2.3
  - statsmodels
  - matplotlib
  - scipy
  - seaborn
  - scikit-learn
  - papermill
  - ipykernel
