name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - pandas
  - numpy
  - statsmodels
  - matplotlib
  - scipy
  - seaborn
  - sklearn
  - papermill
  - ipykernel