name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - pandas
  - scikit-posthocs
  - kmodes
  - numpy<=2.3
  - matplotlib
  - plotly
  - scipy
  - seaborn
  - papermill
  - ipykernel
