name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - r-tidyr
  - r-caret
  - r-readr
  - r-doParallel
  - r-iml
  - r-xgboost
  - r-nnet
  - r-scales
  - r-MASS
  - r-ggplot2
  - r-randomForest
  - r-fastICA
  - r-e1071
  - r-dplyr
  - r-Metrics
  - papermill
  - ipykernel