name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - r-caret
  - r-doParallel
  - r-ggplot2
  - r-randomForest
  - r-fastICA
  - r-Metrics
  - papermill
  - ipykernel